version: "3.5"

services:
  redis:
    env_file:
      - .env
    image: redis/redis-stack:7.0.2-RC1
#    ports:
#      - 6379:6379
#      - 8001:8001

  web:
    build: .
    tty: true
    env_file:
      - .env
    environment:
      REDIS_HOST: redis
      EXCHANGE_API_KEY: ${EXCHANGE_API_KEY}
      APPLICATION_PORT: ${APPLICATION_PORT}
      AUTH_TOKEN: ${AUTH_TOKEN}
    depends_on:
      - redis

  nginx:
    env_file:
      - .env
    image: nginx:1.23-alpine
    ports:
      - ${NGINX_HOST_PORT:-8080}:80
    volumes:
      - ./nginx/templates:/etc/nginx/templates
    environment:
      NGINX_ENVSUBST_OUTPUT_DIR: /etc/nginx/
      APPLICATION_PORT: ${APPLICATION_PORT-3000}
    depends_on:
      - web
